runtime: python39
handlers:
  - url: /style.css
    static_files: /style.css
    upload: /style.css
    mime_type: text/css

  - url: /(.*\.(html|htm))$
    static_files: /\1
    upload: /.*\.(html|htm)$
    mime_type: text/html
